In [1]:
import numpy as np
import pandas as pd
#import datetime
#import openpyxl     #A library that reads/writes Excel files
#import os

In [2]:
Vanguard_overall = -17.32   #Vanguard YTD as of 8/25/2022
iShares_overall = -19.22    #iShares YTD as of 8/25/2022

**Read Excel File using pandas**

In [3]:
active_weight = pd.read_excel(r'/Users/weijunyi/Desktop/GIF_DATA/Active_Weights_asof08_25_2022.xlsx')
historical_closes = pd.read_excel(r'/Users/weijunyi/Desktop/GIF_DATA/GIF_historical_closes08.25.2022.xlsx')
cost_basis = pd.read_excel(r'/Users/weijunyi/Desktop/GIF_DATA/GIF_CostBasis_asof08.25.2022.xlsx')

In [4]:
active_weight.head()    #a glance of active_weight dataframe
#I added two cloumns before reading the Excel file into pandas: Vangard_YTD, iShares_YTD

,Unnamed: 0,GICS_Sector,GIF_Weight,ACWI_Weight,Active_Weight,Vangard_YTD,iShares_YTD
0,0,Cash,4.884114,0.00,4.884114,0.0,0.0
1,1,Communication Services,4.524107,7.64,-3.115893,-30.4,-23.6
2,2,Consumer Discretionary,6.010491,11.16,-5.149509,-23.5,-23.5
3,3,Consumer Staples,9.332454,7.65,1.682454,-4.1,-0.3
4,4,Energy,4.254405,5.21,-0.955595,49.8,48.6

In [5]:
historical_closes.head()  #a glance of historical_closes

,Unnamed: 0,Ticker,2021-12-31 00:00:00,2022-01-03 00:00:00,2022-01-04 00:00:00,2022-01-05 00:00:00,2022-01-06 00:00:00,2022-01-07 00:00:00,2022-01-10 00:00:00,2022-01-11 00:00:00,...,Total_Shares,Total_Cost,Cost_Basis,Entry Year,Latest_Total_Value,YTD_Perf_dollar,Beginning_value,YTD_Perf_percent,LTD_unrealized_price_perf,LTD_unrealized_percent
0,0,AON,300.559998,293.239990,294.269989,293.000000,290.500000,282.779999,282.000000,287.700012,...,127.0,30222.19,237.970000,2021.0,36860.478760,-10.320007,38171.119690,-0.034336,6638.288760,0.219649
1,1,AAPL,177.570007,182.009995,179.699997,174.919998,172.000000,172.169998,172.190002,175.080002,...,245.0,1470.25,6.001020,2007.0,41657.349701,-7.540009,43504.651794,-0.042462,40187.099701,27.333515
2,2,BRK-B,299.000000,300.790009,308.529999,309.920013,313.220001,319.779999,318.929993,319.799988,...,80.0,15840.33,198.004125,2021.0,23850.400391,-0.869995,23920.000000,-0.002910,8010.070391,0.505676
3,3,CAT,206.740005,207.000000,218.080002,219.750000,221.990005,224.190002,221.639999,219.949997,...,91.0,5241.40,57.597802,2010.0,18098.080444,-7.860001,18813.340500,-0.038019,12856.680444,2.452910
4,4,CI,229.630005,234.199997,233.300003,236.520004,227.539993,233.179993,233.690002,240.139999,...,152.0,29998.11,197.355987,2021.0,44361.200928,62.220001,34903.760742,0.270958,14363.090928,0.478800

In [6]:
cost_basis.head()   #a glance of cost basis

,Unnamed: 0,Name,Ticker,Total_Shares,Total_Cost,Cost_Basis,Report_data,Holding,Entry Year,Entry_date,Asset,GeoRaw,Geo Region,Business,GICS_Sector,GIF Sector
0,0,AON PLC CL A,AON,127,30222.19,237.970000,08/25/2022,NaN,2021,2021-04-19 00:00:00,Equity,"Metropolitan Building, James Joyce Street, DUB...",EMEA,Insurance,Financials,Financials & Real Estate
1,1,APPLE INC,AAPL,245,1470.25,6.001020,08/25/2022,NaN,2007,11/15/2007,Equity,"1 Apple Park Way, CUPERTINO, CA, 95014-0642 US",North America,"Computers, Phones & Household Electronics",Information Technology,Technology
2,2,BERKSHIRE HATHAWAY CL-B NEW,BRK-B,80,15840.33,198.004125,08/25/2022,NaN,2021,2013-01-25 00:00:00,Equity,"3555 Farnam St, OMAHA, NE, 68131-3311 US",North America,Consumer Goods Conglomerates,Financials,Financials & Real Estate
3,3,CATERPILLAR INC,CAT,91,5241.40,57.597802,08/25/2022,NaN,2010,02/18/2010,Equity,"510 Lake Cook Rd Ste 100, DEERFIELD, IL, 60015...",North America,"Machinery, Equipment & Components",Industrials,"Energy, Industrials, Materials & Utilities"
4,4,CIGNA CORP,CI,152,29998.11,197.355987,08/25/2022,NaN,2021,2021-12-01 00:00:00,Equity,"900 Cottage Grove Road, BLOOMFIELD, CT, 06002-...",North America,Healthcare Providers & Services,Healthcare,Healthcare

In [7]:
GICS_sector = cost_basis.iloc[:,-2]    #extract sector classification from cost_basis
GIF_sector = cost_basis.iloc[:,-1]

In [8]:
assigned_df = historical_closes.assign(GIF_sector = GIF_sector)     #add GIF_sector to historical_closes as a new column
assigned_df = assigned_df.assign(GICS_sector = GICS_sector)         #same as above
assigned_df.head()

,Unnamed: 0,Ticker,2021-12-31 00:00:00,2022-01-03 00:00:00,2022-01-04 00:00:00,2022-01-05 00:00:00,2022-01-06 00:00:00,2022-01-07 00:00:00,2022-01-10 00:00:00,2022-01-11 00:00:00,...,Cost_Basis,Entry Year,Latest_Total_Value,YTD_Perf_dollar,Beginning_value,YTD_Perf_percent,LTD_unrealized_price_perf,LTD_unrealized_percent,GIF_sector,GICS_sector
0,0,AON,300.559998,293.239990,294.269989,293.000000,290.500000,282.779999,282.000000,287.700012,...,237.970000,2021.0,36860.478760,-10.320007,38171.119690,-0.034336,6638.288760,0.219649,Financials & Real Estate,Financials
1,1,AAPL,177.570007,182.009995,179.699997,174.919998,172.000000,172.169998,172.190002,175.080002,...,6.001020,2007.0,41657.349701,-7.540009,43504.651794,-0.042462,40187.099701,27.333515,Technology,Information Technology
2,2,BRK-B,299.000000,300.790009,308.529999,309.920013,313.220001,319.779999,318.929993,319.799988,...,198.004125,2021.0,23850.400391,-0.869995,23920.000000,-0.002910,8010.070391,0.505676,Financials & Real Estate,Financials
3,3,CAT,206.740005,207.000000,218.080002,219.750000,221.990005,224.190002,221.639999,219.949997,...,57.597802,2010.0,18098.080444,-7.860001,18813.340500,-0.038019,12856.680444,2.452910,"Energy, Industrials, Materials & Utilities",Industrials
4,4,CI,229.630005,234.199997,233.300003,236.520004,227.539993,233.179993,233.690002,240.139999,...,197.355987,2021.0,44361.200928,62.220001,34903.760742,0.270958,14363.090928,0.478800,Healthcare,Healthcare

In [9]:
sort_by = assigned_df.sort_values(by=['GIF_sector'])   #sort by sector
sort_by.head()

,Unnamed: 0,Ticker,2021-12-31 00:00:00,2022-01-03 00:00:00,2022-01-04 00:00:00,2022-01-05 00:00:00,2022-01-06 00:00:00,2022-01-07 00:00:00,2022-01-10 00:00:00,2022-01-11 00:00:00,...,Cost_Basis,Entry Year,Latest_Total_Value,YTD_Perf_dollar,Beginning_value,YTD_Perf_percent,LTD_unrealized_price_perf,LTD_unrealized_percent,GIF_sector,GICS_sector
19,19,DIS,154.889999,156.759995,155.729996,155.190002,156.899994,157.830002,156.600006,157.889999,...,99.223800,2016.0,11745.999908,-37.430000,15488.999939,-0.241655,1823.619908,0.183789,Communication Services,Communication Services
17,17,VZ,51.959999,52.439999,53.470001,54.020000,53.759998,54.240002,53.869999,53.590000,...,51.801825,2021.0,12465.900478,-8.219997,14808.599739,-0.158199,-2297.619522,-0.155628,Communication Services,Communication Services
31,31,VOX,135.559998,136.509995,135.869995,132.119995,132.550003,132.600006,132.399994,133.990005,...,124.169391,2022.0,11378.100281,-25.229389,14279.480000,-0.203185,-2901.379719,-0.203185,Communication Services,Communication Services
18,18,WMT,144.690002,144.649994,142.000000,143.919998,143.520004,144.889999,144.610001,144.199997,...,136.270000,2021.0,42391.438477,-8.820007,45143.280762,-0.060958,-124.801523,-0.002935,Consumer Staples & Discrecionary,Consumer Staples
5,5,DHI,108.449997,105.260002,105.720001,103.070000,101.500000,95.239998,95.720001,98.730003,...,89.027689,2021.0,17237.250137,-31.839996,24401.249313,-0.293591,-2793.979863,-0.139481,Consumer Staples & Discrecionary,Consumer Discretionary

In [10]:
'''groupping each sector into different dataframes'''
communication_service = sort_by.iloc[:3]
consumer_staple_dis = sort_by.iloc[3:9]
energy_industrial_material_utility = sort_by.iloc[9:17]
financial_real_estate = sort_by.iloc[17:24]
healthcare = sort_by.iloc[24:27]
technology = sort_by.iloc[27:33]

In [11]:
'''calculate sector performance: YTD'''
#communication service sector = -20.160762157093284%
comm_serv_begin = communication_service.iloc[:,-6].sum()
comm_serv_latest = communication_service.iloc[:,-8].sum()
comm_serv_return = 100*(comm_serv_latest - comm_serv_begin)/comm_serv_begin

#consumer staple discretionary sector = -14.681833268597769%
consumer_begin = consumer_staple_dis.iloc[:,-6].sum()
consumer_latest = consumer_staple_dis.iloc[:,-8].sum()
consumer_return = 100*(consumer_latest - consumer_begin)/consumer_begin

#energy, industial, material, & utility sector = 3.8503056863193144%
ener_ind_mat_uti_begin = energy_industrial_material_utility.iloc[:,-6].sum()
ener_ind_mat_uti_latest = energy_industrial_material_utility.iloc[:,-8].sum()
ener_ind_mat_uti_return = 100*(ener_ind_mat_uti_latest - ener_ind_mat_uti_begin)/ener_ind_mat_uti_begin

#financial & real estate sector = -7.092909588825769
fin_estate_begin = financial_real_estate.iloc[:,-6].sum()
fin_estate_latest = financial_real_estate.iloc[:,-8].sum()
fin_estate_return = 100*(fin_estate_latest - fin_estate_begin)/fin_estate_begin

#healthcare sector = 18.41001786831249%
healthcare_begin = healthcare.iloc[:,-6].sum()
healthcare_latest = healthcare.iloc[:,-8].sum()
healthcare_return = 100*(healthcare_latest - healthcare_begin)/healthcare_begin

#technology sector = -18.31467987177053
technology_begin = technology.iloc[:,-6].sum()
technology_latest = technology.iloc[:,-8].sum()
technology_return = 100*(technology_latest - technology_begin)/technology_begin

In [12]:
active_weight

,Unnamed: 0,GICS_Sector,GIF_Weight,ACWI_Weight,Active_Weight,Vangard_YTD,iShares_YTD
0,0,Cash,4.884114,0.00,4.884114,0.00,0.00
1,1,Communication Services,4.524107,7.64,-3.115893,-30.40,-23.60
2,2,Consumer Discretionary,6.010491,11.16,-5.149509,-23.50,-23.50
3,3,Consumer Staples,9.332454,7.65,1.682454,-4.10,-0.30
4,4,Energy,4.254405,5.21,-0.955595,49.80,48.60
5,5,Financials,16.282619,15.40,0.882619,-14.30,-13.80
6,6,Healthcare,16.134985,12.34,3.794985,-12.10,-12.20
7,7,Industrials,8.035865,9.68,-1.644135,-12.00,-15.50
8,8,Information Technology,17.270550,20.43,-3.159450,-22.80,-26.40
9,9,Materials,4.646547,4.51,0.136547,-13.80,-12.20
10,10,Real Estate,3.428905,2.82,0.608905,-13.63,-17.86
11,11,Utilities,5.194960,3.14,2.054960,5.30,5.10

In [13]:
'''
    Now we need to make our sector performance comparable to the ACWI ETF performance, 
    so we regroup GICS_sector into 6 new sectors which is the same as GIF_sector and 
    recalculate it's weighting and performance.
    
    Sector Abbreviation:
    Energy, Industrial, Material, &utility = eimu
    Consumer Staple & Discretionary = csd
    Financial & Real Estate = fr
    Healthcare = health
    Technology = tech
    Communication Service = cs
'''

"\n    Now we need to make our sector performance comparable to the ACWI ETF performance, \n    so we regroup GICS_sector into 6 new sectors which is the same as GIF_sector and \n    recalculate it's weighting and performance.\n    \n    Sector Abbreviation:\n    Energy, Industrial, Material, &utility = eimu\n    Consumer Staple & Discretionary = csd\n    Financial & Real Estate = fr\n    Healthcare = health\n    Technology = tech\n    Communication Service = cs\n"

In [14]:
GIF_eimu_weight = 4.254405 + 8.035865 + 4.646547 + 5.194960
GIF_csd_weight = 6.010491 + 9.332454
GIF_fr_weight = 16.282619 + 3.428905
GIF_health_weight = 16.134985
GIF_tech_weight = 17.270550
GIF_cs_weight = 4.524107

In [15]:
ACWI_eimu_weight = 5.21 + 9.68 + 4.51 + 3.14
ACWI_csd_weight = 11.16 + 7.65
ACWI_fr_weight = 15.4 + 2.82
ACWI_health_weight = 12.34
ACWI_tech_weight = 20.43
ACWI_cs_weight = 7.64

ACWI_eimu_return = (5.21/ACWI_eimu_weight)*49.80 \
                    +(9.68/ACWI_eimu_weight)*(-12) \
                    +(4.51/ACWI_eimu_weight)*(-13.8) \
                    +(3.14/ACWI_eimu_weight)*(5.3)
ACWI_csd_return = (11.16/ACWI_csd_weight)*(-23.5) \
                    +(7.65/ACWI_csd_weight)*(-4.1)
ACWI_fr_return = (15.40/ACWI_fr_weight)*(-14.3) \
                    +(2.82/ACWI_fr_weight)*(-13.63)
ACWI_health_return = -12.1
ACWI_tech_return = -22.8
ACWI_cs_return = -30.4

In [16]:
'''Make array to make easier to calculate'''
l_GIF_weight = np.array([GIF_eimu_weight,GIF_csd_weight,GIF_fr_weight,GIF_health_weight,GIF_tech_weight,GIF_cs_weight])
l_GIF_return = np.array([ener_ind_mat_uti_return,consumer_return,fin_estate_return,healthcare_return,technology_return,comm_serv_return])
l_ACWI_weight = np.array([ACWI_eimu_weight,ACWI_csd_weight,ACWI_fr_weight,ACWI_health_weight,ACWI_tech_weight,ACWI_cs_weight])
#use Vanguard return as a temporary solution
l_ACWI_return = np.array([ACWI_eimu_return,ACWI_csd_return,ACWI_fr_return,ACWI_health_return,ACWI_tech_return,ACWI_cs_return])
benchmark_return = -17.32

In [1]:
def brinson_fachler(wi, Wi, Ri, Bi, B):
    A = 0  #allocation effect
    wi = wi/100
    Wi = Wi/100
    Ri = Ri/100
    Bi = Bi/100
    B = B/100
    for k in range(len(wi)):
        Ai = (wi[k] - Wi[k])*(Bi[k] - B)
        A += Ai
    
    S = 0  #selection effect
    for k in range(len(wi)):
        Si = Wi[k]*(Ri[k] - Bi[k])
        S += Si
    
    I = 0  #interaction effect
    for k in range(len(wi)):
        Ii = (wi[k] - Wi[k])*(Ri[k] - Bi[k])
        I += Si
    
    return A*100, S*100, I*100

In [2]:
A, S, I = brinson_fachler(l_GIF_weight, l_ACWI_weight, l_GIF_return, l_ACWI_return, benchmark_return)
print(A, S, I)

NameError: name 'l_GIF_weight' is not defined